# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: miska.me
email: hello@miska.me
description: >
  Michael Hamilton's development blog and other development related goodies.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /blog/:title
url: "http://miska.me" # the base hostname & protocol for your site
twitter_username: miskahamilton
github_username:  michael-hamilton

# Build settings
markdown: kramdown